var d = new Date();
 var n = d.getTimezoneOffset();
var h = d.getHours();
var day = d.getDate();
var month = d.getMonth()+1;
var year = d.getFullYear();
d.getFullYear();
var date = day + "/" + month + "/" + year;
//document.write(date);
//alert(h);